### ISSUE TITLE
Span needs thread-locals initialized

### ISSUE THREAD

**Issue by kornelski** [google/rerast#16]
Transforming glutin on Linux (4.4.0-116-generic #140-Ubuntu x86_64), rustc 1.27.0-nightly (ac3c2288f 2018-04-18), with rules:

```rust
fn rule1<T,E,X: From<E>>(r: Result<T,E>) -> Result<T,X> {
    replace!(try!(r) => r?);
    unreachable!()
}
```

I get

```
thread 'main' panicked at 'cannot access a scoped thread local variable without calling `set` first', /cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.1/src/lib.rs:186:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:205
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:461
   6: std::panicking::begin_panic
   7: <scoped_tls::ScopedKey<T>>::with
   8: syntax_pos::<impl core::cmp::PartialOrd for syntax_pos::span_encoding::Span>::partial_cmp
   9: alloc::slice::<impl [T]>::sort::{{closure}}
  10: alloc::slice::merge_sort
  11: rerast::code_substitution::FileRelativeSubstitutions::merge
  12: rerast::RerastOutput::merge
  13: cargo_rerast::cargo_rerast
  14: cargo_rerast::main
```

https://github.com/rust-lang-nursery/rustfmt/issues/2532 suggests calling `syntax::with_globals` before using parser.

**Comment by davidlattimore** [comment]
Thanks. That would be related to my fix for #13 yesterday. Not sure why my test doesn't trigger it though.
